### ISSUE TITLE
Issues in Scheduling with CronR

### ISSUE THREAD

**Issue by jake22anderson** [tonytrevisan/rameritrade#3]
I am trying to use this (great) package to text myself updates on my portfolio at certain times of the day, but I am having issues with CronR. A function of mine calls `rameritrade::td_auth_accessToken(consumerKey, refreshToken)`, which appears to be the cause of the issue. It should be noted that this message does not appear when running it manually, only when I attempt to schedule it. The error message in my log is:
"Error in ram_checkRefresh(refreshToken) : 
  Incorrect object type passed as Refresh Token. Please pass the output from auth_init_refreshToken or auth_new_refreshToken.FALSE
Calls: get_acct -> <Anonymous> -> ram_checkRefresh
Execution halted"

Thanks for any and all assistance.

**Comment by tonytrevisan** [comment]
Thanks for the feedback. If you run the code outside of a Cron job does it work? I run a lot of my code within cron and don’t have any issues, so I don’t think it’s an issue with cron. 

Are you modifying the refresh token at all? The TD auth_access_token  specifically checks that the refresh token is the exact output from init/new_refresh_token. This means it is looking for a list object. Don’t pull the refresh token string out of the list object. 

>

**Comment by tonytrevisan** [comment]
I found an issue with running scripts through other programs such as test_that where it was throwing the error you saw. There must be a loaded library in CronR creating a conflict with one of the checks. I modified the code and pushed up the changes. Try installing with devtools::install_github("tonytrevisan/rameritrade") and running again.
